[package]
name = "extract-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
yaml-rust = "0.4.4"
walkdir = "2.3.3"
camino = "1.1.4"
tui = "0.19.0"
crossterm = "0.26.1"
